from fortes_webservice_wrapper.wrapper.fortes_ws import FortesWrapper

cliente = {
    "codigo": "",
    "nome": "Ana do Imobanco",
    "nomeFantasia": "ImoAna",
    "cnpjcpf": "57632889043",
    "cep": "60015140",
    "logradouro": "Rua Teresa Cristina",
    "bairro": "Centro",
    "numero": "",
    "complemento": " ",
    "uf": "CE",
    "cidade": "04400",
    "ddd": "",
    "fone": "",
    "fax": "",
    "identificador": "",
    "celular": "",
    "email": "",
    "contato": "",
    "site": "",
    "rg": "",
    "ie": "",
    "grupo": "0001",
    "agenteCobrador": "",
    "receita": "",
    "contaContabil": "",
    "Representante": "",
    "Vencimento": 10,
    "Etiqueta": 0,
    "GeraNFAuto": 0,
    "RetemISS": 0,
    "RetemINSS": 0,
    "AliquotaISS": 0,
    "IM": "",
    "CampoExtra1": "",
    "CampoExtra2": "",
    "CampoExtra3": "",
    "CampoExtra4": "",
    "CampoExtra5": "",
    "CampoExtra6": "",
    "CampoExtra7": "",
    "CampoExtra8": "",
    "CampoExtra9": "",
    "CampoExtra10": "",
}

r = FortesWrapper().alterar_cliente(cliente)
